name: Conditional Auto Deploy on Baseline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '#deploy')  # Check for the specific flag in commit message
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server:
          - BASELINE

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_BASELINE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Debug SSH Key Setup
        run: |
          ls -la ~/.ssh
          cat ~/.ssh/id_rsa
        shell: bash
      
      - name: Deploy to server
        run: ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@baseline.chirp.digital "echo Connection successful"
        shell: bash
      
      