name: Conditional Auto Deploy on Baseline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '#deploy')  # Check for the specific flag in commit message
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server:
          - BASELINE

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH agent
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_BASELINE }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets[format('SERVER_HOST_{0}', matrix.server)] }} >> ~/.ssh/known_hosts

        # Test SSH Connection
      - name: Test SSH Connection
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_BASELINE }}@${{ secrets.SERVER_HOST_BASELINE }} "echo Connection successful"

      # Deploy to each server
    #   - name: Deploy to server
    #     run: |
    #       ssh ${{ secrets.SERVER_USER_BASELINE }}@${{ secrets[format('SERVER_HOST_{0}', matrix.server)] }} << 'EOF'
    #         cd /home/deploy_test
  
    #         mkdir auto_deploy_test
    #       EOF
            

