name: Conditional Auto Deploy on Baseline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '#deploy')  # Check for the specific flag in commit message
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server:
          - BASELINE

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH agent
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key with passphrase
        env:
          SSH_PASSPHRASE: ${{ secrets.SERVER_PASSPHRASE_BASELINE }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SECRET_PEM_KEY_BASELINE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -f ~/.ssh/id_rsa -y >/dev/null <<< "$SSH_PASSPHRASE"

      - name: Add server to known hosts
        run: ssh-keyscan -H your-server.com >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@your-server.com "echo Connection successful"
            

