name: Conditional Auto Deploy on Baseline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '#deploy')
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH key from secrets
      - name: Set up SSH key and passphrase
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_CHIRP }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Start the SSH agent
          eval "$(ssh-agent -s)"

          # Add the private key with the passphrase
          echo "${{ secrets.SERVER_PASSPHRASE_BASELINE }}" | ssh-add <(echo "${{ secrets.SSH_KEY_CHIRP }}")

          # Add GitHub Actions known_hosts (to skip host verification)
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SERVER_HOST_BASELINE }} >> ~/.ssh/known_hosts

      # Test SSH Connection with Debugging
      - name: Test SSH Connection with Debugging
        run: |
          ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_BASELINE }}@${{ secrets.SERVER_HOST_BASELINE }} "echo Connection successful"
