name: Conditional Auto Deploy on Baseline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '#deploy')  # Check for the specific flag in commit message
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server:
          - BASELINE

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_BASELINE }}" > ~/.ssh/id_rsa.pem
          chmod 600 ~/.ssh/id_rsa.pem
        shell: bash
      
      - name: Start SSH agent
        env:
          SSH_PASSPHRASE: ${{ secrets.SERVER_PASSPHRASE_BASELINE }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa.pem <<< "${{ secrets.SERVER_PASSPHRASE_BASELINE }}"
        shell: bash
      
      - name: Add server to known hosts
        run: |
          ssh-keyscan -H baseline.chirp.digital >> ~/.ssh/known_hosts
        shell: bash
      
      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa.pem -o StrictHostKeyChecking=no root@baseline.chirp.digital "echo Connection successful"
        shell: bash
      